### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by benwilson512** [ex-aws/ex_aws_sqs#1]
Hey @TattdCodeMonkey, per https://elixirforum.com/t/proposal-exaws-2-0/9269 the ExAws project is splitting out each service into its own project.

You are the original contributor the SQS service to ExAws. If you wish to be its maintainer, please let me know and I will give you commit access to this repository. If you do not want this, let me know and I will look for someone else.

Thank you!

**Comment by TattdCodeMonkey** [comment]
@benwilson512 I'd be happy to be a maintainer. 

@adamkittelson actually did the brunt of the work after I started it, so if they were interested I would be happy to let them take it or share.

https://github.com/ex-aws/ex_aws/pull/56
