### ISSUE TITLE
Error when publishing message to SQS

### ISSUE THREAD

**Issue by gvn182** [ex-aws/ex_aws_sqs#23]
### Environment
* Elixir & Erlang versions (elixir --version): Elixir 1.10.2 (compiled with Erlang/OTP 22)
* ExAws version `mix deps |grep ex_aws`: 

* ex_aws 2.1.2 (Hex package) (mix)
  locked at 2.1.2 (ex_aws) b1d24a9a
* ex_aws_sqs 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (ex_aws_sqs) ddb26bce

* HTTP client version. IE for hackney do `mix deps | grep hackney`: hackney 1.15.2 (Hex package) (rebar3)
      {:ex_aws_sqs, "~> 3.1"},
      {:jason, "~> 1.1"},
      {:poison, "~> 3.0"},
      {:hackney, "~> 1.9"},
      {:sweet_xml, "~> 0.6"},

### Current behavior
Sometimes when trying to publish a message, I receive an error
This is the code I'm using to publish:

body = %{message: message_params, user: %{id: token[:sub]}, msg_id: msg_id}
payload = Jason.encode!(body)
envs[:queue_outbound_name]
|> SQS.send_message(payload)
|> ExAws.request()

Most of the time all messages work, but sometimes I receive:

`Elixir.RuntimeError: ** (exit) {:fatal, {:expected_element_start_tag, {:file, :file_name_unknown}, {:line, 1}, {:col, 1}}}
    (xmerl) xmerl_scan.erl:4124: :xmerl_scan.fatal/2
    (xmerl) xmerl_scan.erl:572: :xmerl_scan.scan_document/2
    (xmerl) xmerl_scan.erl:291: :xmerl_scan.string/2
    (sweet_xml) lib/sweet_xml.ex:237: SweetXml.parse/2
    (sweet_xml) lib/sweet_xml.ex:421: SweetXml.xpath/2
    (sweet_xml) lib/sweet_xml.ex:454: SweetXml.xpath/3
    (ex_aws_sqs) lib/ex_aws/sqs/sweet_xml_parser.ex:11: ExAws.SQS.SweetXmlParser.parse/2
    (xxx) web/controllers/message_controller.ex:21: Hermesapi.MessageController.create/2`

### Expected behavior
Sometimes the same content works and sometimes don't.

I didn't try to change the dep to Saxy, should I?

**Comment by TattdCodeMonkey** [comment]
@gvn182 I would give Saxy a try and see if you see the same issue. Saxy also seems to have better performance for what that is worth.

**Comment by gvn182** [comment]
Same problem guys, but now the message is:


``Elixir.Saxy.ParseError: unexpected end of input, expected token: :lt
    (ex_aws_sqs) lib/ex_aws/sqs/saxy_collector.ex:93: ExAws.SQS.SaxyCollector.parse_string!/2
    (ex_aws_sqs) lib/ex_aws/sqs/saxy_parser.ex:261: ExAws.SQS.SaxyParser.parse/2
    (hermesapi) web/controllers/message_controller.ex:21: Hermesapi.MessageController.create/2
    (hermesapi) web/controllers/message_controller.ex:1: Hermesapi.MessageController.action/2
    (hermesapi) web/controllers/message_controller.ex:1: Hermesapi.MessageController.phoenix_controller_pipeline/2
    (hermesapi) lib/hermesapi/endpoint.ex:1: Hermesapi.Endpoint.instrument/4
    (hermesapi) lib/spandex_phoenix.ex:156: Hermesapi.MessageController.call/2
    (phoenix) lib/phoenix/router.ex:278: Phoenix.Router._call_/1``


I gave up for now and migrated to python.

**Comment by TattdCodeMonkey** [comment]
This seems like an impartial response is trying to be processed, which I'm not sure where in the stack the issue would be, but I don't think it would be in this library.

@benwilson512  have you ever seen anything like this before?

**Comment by benwilson512** [comment]
I have not, I'd try to get a hold of the raw response from AWS to diagnose further.

**Comment by ChezCrawford** [comment]
@gvn182 : any chance you had a quasi-reliable way of reproducing this issue?
