### ISSUE TITLE
Please publish #4 to hex

### ISSUE THREAD

**Issue by sneako** [ex-aws/ex_aws_sqs#5]
I am unable to add ex_aws_sqs to my project that is already on ex_aws 2.1, without downgrading ex_aws or referencing github due to the issue fixed in #4. Could you please push this change to hex?

**Comment by gfikes** [comment]
Any chance of getting this released to hex soon? Would like to move to ex_aws 2.1 as well.

**Comment by billgloff** [comment]
It's been awhile since there's been any activity with this package?   Do the maintainers need any help with anything?   Is there any way we can get a new hex release?    Let us know!  Thanks!

**Comment by TattdCodeMonkey** [comment]
@benwilson512 can a new version be published?

**Comment by toddholmberg** [comment]
Is it possible to get this version published to hex soon? Broadway is out, with specific examples for working with SQS, so it would be great if we could use ex_aws 2.1 with ex_aws_sqs. Also, I am working on a project that will require both ex_aws_sqs and ex_aws_secretsmanager. ex_aws 2.0 complains that secretsmanager is not in the aws partition, while ex_aws 2.1 works just fine with ex_aws_secretsmanager. Please, please, please relax the version dependency. Thanks!

**Comment by hykw** [comment]
@benwilson512 
Thank you for providing the great package!
I'd appreciate you publish the new version when there is time.

**Comment by prokopyl** [comment]
@TattdCodeMonkey @benwilson512 Is this package still maintained?

From what I understood scavenging the issues around here, it seems @TattdCodeMonkey has been given maintainer status from @benwilson512 , but it seems he doesn't have the needed permissions to publish new releases.

As per https://elixirforum.com/t/proposal-exaws-2-0/9269, it is perfectly reasonable that you don't want to maintain all the services' packages yourself @benwilson512 , but then please allow the other maintainers to publish updates.

For the record, I am an user of AWS SQS professionally, trying to make use of ExAws both directly and through [broadway](https://github.com/plataformatec/broadway), which logically uses this package to talk to SQS, and seems to be getting quite a bit of traction from the Elixir community as a whole, and them relying on a virtually-dead package is a very serious issue.

I have found a few issues during my experiments, which I would be glad to both report, help on and submit PRs for, however it would just be a complete waste if those contributions never get released.

**Comment by benwilson512** [comment]
@TattdCodeMonkey contact me with your hex.pm username so I can give you push credentials.

**Comment by TattdCodeMonkey** [comment]
`v2.0.1` has been released to [hex](https://hex.pm/packages/ex_aws_sqs/2.0.1)
